APP_DIR = /usr/share/applications
ICON_DIR = /usr/share/icons

all: 
	@[ -d $(APP_DIR) ] || mkdir -p $(APP_DIR)
	cp matlab_ScrnCtrlApp.desktop $(APP_DIR)
	cp matlab_su.desktop $(APP_DIR)
	@[ -d $(ICON_DIR) ] || mkdir -p $(ICON_DIR)
	cp ratHead.png $(ICON_DIR)
